version: "3"

services:
  sample_db:
    image: postgres:14-alpine
    volumes:
      - ./migrations/up/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: verysecret
    ports:
      - '5432:5432'
